apiVersion: v1
kind: Service
metadata:
  name: agentapi
  labels:
    app: agentapi
spec:
  type: ClusterIP
  selector:
    app: agentapi
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
